name: Notify and Build Docker on Commit

on:
  push:
    branches:
      - "master"

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Push Notification via Pushover
        run: |
          curl -s \
          --form-string "token=az4r2jtfbk3tb9oepic9hz8y5dqvdi" \
          --form-string "user=ug9baaoiacgcx4cgqx6773nx1o6awp" \
          --form-string "message=New commit by ${{ github.actor }}. Commit message: ${{ github.event.head_commit.message }}" \
          https://api.pushover.net/1/messages.json

  docker:
    runs-on: ubuntu-latest
    needs: notify
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hstefov/devops-project-app:latest
